"""
datos_cud.py
Base de datos del trámite CUD — requisitos, juntas, beneficios, formularios.
Fuente: ANDIS argentina.gob.ar/andis + PDF oficial Ministerio de Transporte
Juntas evaluadoras: 24 provincias completas — datos oficiales 2024.
"""

FORMULARIOS = [{'id': 'solicitud_cud',
  'nombre': 'Solicitud de CUD — Formulario online ANDIS',
  'descripcion': 'Formulario principal para iniciar el trámite del CUD. Completá el cuestionario online para saber qué planilla corresponde a tu situación.',
  'url': 'https://www.argentina.gob.ar/cud/consulta-de-requisitos-para-tramitar-el-cud',
  'url_online': 'https://www.argentina.gob.ar/cud/como-obtener-el-certificado-unico-de-discapacidad-cud',
  'formato': 'Formulario online',
  'obligatorio': True},
 {'id': 'declaracion_jurada',
  'nombre': 'Declaración Jurada de Ingresos',
  'descripcion': 'Requerida para solicitar pensión no contributiva por invalidez. Se descarga desde el portal ANDIS según el tipo de discapacidad.',
  'url': 'https://www.argentina.gob.ar/andis/pensiones-no-contributivas-por-invalidez',
  'url_online': 'https://www.argentina.gob.ar/andis',
  'formato': 'PDF (disponible en la junta evaluadora)',
  'obligatorio': False},
 {'id': 'autorizacion_tercero',
  'nombre': 'Autorización para tramitar por tercero',
  'descripcion': 'Cuando el trámite lo realiza un familiar, tutor o representante legal. Debe ser manuscrita y firmada por el titular.',
  'url': 'https://www.argentina.gob.ar/cud/como-obtener-el-certificado-unico-de-discapacidad-cud',
  'url_online': None,
  'formato': 'Manuscrita firmada (no requiere formulario oficial)',
  'obligatorio': False}]


REQUISITOS_GENERALES = [{'orden': 1,
  'documento': 'DNI original y fotocopia',
  'detalle': 'Vigente. Para menores: DNI del menor y del adulto responsable.',
  'obligatorio': True},
 {'orden': 2,
  'documento': 'Formulario de solicitud completo',
  'detalle': 'Descargar y completar el formulario oficial de ANDIS antes del turno.',
  'obligatorio': True,
  'url_descarga': 'https://www.argentina.gob.ar/cud/como-obtener-el-certificado-unico-de-discapacidad-cud'},
 {'orden': 3,
  'documento': 'Historia clínica o informe médico actualizado',
  'detalle': 'Emitido por médico matriculado. Diagnóstico, evolución y limitaciones funcionales. '
             'Antigüedad máxima recomendada: 6 meses.',
  'obligatorio': True},
 {'orden': 4,
  'documento': 'Estudios complementarios según tipo de discapacidad',
  'detalle': 'Análisis, imágenes, informes de especialistas según corresponda.',
  'obligatorio': True},
 {'orden': 5,
  'documento': '2 fotos 4x4 fondo blanco',
  'detalle': 'Fotografías recientes del solicitante.',
  'obligatorio': True},
 {'orden': 6,
  'documento': 'Turno previo',
  'detalle': 'Sacar turno online en argentina.gob.ar/tramites/sacar-turno-cud o llamar al 0800 de '
             'ANDIS.',
  'obligatorio': True,
  'url': 'https://www.argentina.gob.ar/tramites/sacar-turno-cud'}]


REQUISITOS_POR_TIPO = {'motora': {'nombre': 'Discapacidad motora',
            'descripcion': 'Afecta el sistema neuromuscular o esquelético.',
            'documentos_adicionales': ['Informe neurológico o traumatológico según corresponda',
                                       'Resonancia magnética o radiografías según diagnóstico',
                                       'Informe de kinesiólogo o fisiatra (evaluación funcional)',
                                       'En caso de amputación: informe del cirujano y/o '
                                       'protetista'],
            'especialidades_evaluadoras': ['Neurólogo', 'Traumatólogo', 'Fisiatra'],
            'tip': 'El informe de evaluación funcional es fundamental para la junta evaluadora.'},
 'visual': {'nombre': 'Discapacidad visual',
            'descripcion': 'Pérdida parcial o total de la visión.',
            'documentos_adicionales': ['Informe oftalmológico con agudeza visual y campo visual '
                                       '(perimetría)',
                                       'Fondo de ojo actualizado',
                                       'En baja visión: informe de rehabilitación visual si '
                                       'existe'],
            'especialidades_evaluadoras': ['Oftalmólogo'],
            'tip': 'El campo visual (perimetría) es el estudio más importante para acreditar '
                   'discapacidad visual.'},
 'auditiva': {'nombre': 'Discapacidad auditiva',
              'descripcion': 'Pérdida parcial o total de la audición.',
              'documentos_adicionales': ['Audiometría tonal y vocal reciente (máx. 6 meses)',
                                         'Logoaudiometría',
                                         'Potenciales evocados auditivos en menores o casos '
                                         'complejos',
                                         'Informe del otorrinolaringólogo o audiólogo'],
              'especialidades_evaluadoras': ['Otorrinolaringólogo', 'Audiólogo'],
              'tip': 'La audiometría debe realizarse sin audífonos para determinar el grado real '
                     'de pérdida.'},
 'intelectual': {'nombre': 'Discapacidad intelectual',
                 'descripcion': 'Alteraciones significativas en la función intelectual.',
                 'documentos_adicionales': ['Evaluación psicológica con test de inteligencia '
                                            '(WISC, WAIS según edad)',
                                            'Informe neurológico o neuropediátrico',
                                            'Informe escolar o de institución educativa especial '
                                            'si aplica',
                                            'Para TEA: informe diagnóstico con escala DSM-5 o '
                                            'CIE-11'],
                 'especialidades_evaluadoras': ['Psicólogo',
                                                'Neurólogo/Neuropediatra',
                                                'Psiquiatra'],
                 'tip': 'Para TEA sin compromiso intelectual el CUD puede otorgarse igualmente. '
                        'Documentar las dificultades en la vida cotidiana.'},
 'psicosocial': {'nombre': 'Discapacidad psicosocial (salud mental)',
                 'descripcion': 'Alteraciones en la conducta adaptativa y la salud mental.',
                 'documentos_adicionales': ['Informe psiquiátrico actualizado con diagnóstico '
                                            'DSM-5/CIE-11',
                                            'Historia clínica de internaciones previas si aplica',
                                            'Informe de psicólogo tratante',
                                            'Constancia de tratamiento actual'],
                 'especialidades_evaluadoras': ['Psiquiatra', 'Psicólogo'],
                 'tip': 'El criterio es la limitación funcional en la vida cotidiana, no solo el '
                        'diagnóstico.'},
 'visceral': {'nombre': 'Discapacidad visceral / orgánica',
              'descripcion': 'Afecta órganos internos.',
              'documentos_adicionales': ['Informe del médico especialista en el órgano afectado',
                                         'Estudios de función orgánica actualizados',
                                         'En insuficiencia renal: informe de nefrología',
                                         'Para enfermedades raras: informe de centro de '
                                         'referencia'],
              'especialidades_evaluadoras': ['Especialista del órgano afectado', 'Médico clínico'],
              'tip': 'Para enfermedades raras, el diagnóstico de un centro de referencia nacional '
                     'tiene mayor peso.'}}


PASOS_TRAMITE = [{'paso': 1,
  'titulo': 'Reunir la documentación',
  'descripcion': 'Juntá el DNI, formulario completado, informes médicos, estudios y fotos.',
  'duracion_estimada': 'Variable — depende de conseguir turnos médicos',
  'url': None,
  'tip': 'Empezá por pedir el informe a tu médico tratante. Explicale que es para el CUD.'},
 {'paso': 2,
  'titulo': 'Sacar turno en la Junta Evaluadora',
  'descripcion': 'Sacá turno online o llamá al 0800 de tu provincia.',
  'duracion_estimada': '1 a 30 días según provincia',
  'url': 'https://www.argentina.gob.ar/tramites/sacar-turno-cud',
  'tip': 'Sacar el turno mientras juntás los documentos para no perder tiempo.'},
 {'paso': 3,
  'titulo': 'Presentarse a la Junta Evaluadora',
  'descripcion': 'Concurrí en la fecha y hora del turno con TODA la documentación.',
  'duracion_estimada': '1 día (la entrevista dura 30-60 min aprox.)',
  'url': None,
  'tip': 'Llevá copias de todo. Si no podés trasladarte, en muchos casos hay evaluación '
         'domiciliaria.'},
 {'paso': 4,
  'titulo': 'Evaluación interdisciplinaria',
  'descripcion': 'La junta evalúa la documentación y al solicitante. Pueden pedir estudios '
                 'adicionales.',
  'duracion_estimada': 'En el momento o hasta 30 días hábiles',
  'url': None,
  'tip': 'Si te piden estudios adicionales, preguntá exactamente qué necesitan y los plazos.'},
 {'paso': 5,
  'titulo': 'Resolución y emisión del CUD',
  'descripcion': 'Si se aprueba, se emite el CUD físico y/o digital (app Mi Argentina).',
  'duracion_estimada': '30 a 90 días hábiles según provincia',
  'url': 'https://www.argentina.gob.ar/andis',
  'tip': 'Podés consultar el estado en argentina.gob.ar/andis/consultas-publicas con tu DNI.'},
 {'paso': 6,
  'titulo': 'Descargar el CUD digital',
  'descripcion': 'Una vez emitido, el CUD digital está disponible en la app Mi Argentina.',
  'duracion_estimada': 'Inmediato una vez notificado',
  'url': 'https://mi.argentina.gob.ar',
  'tip': 'El CUD digital tiene la misma validez legal que el físico.'}]


BENEFICIOS = [{'categoria': 'Salud',
  'icono': '🏥',
  'beneficios': [{'nombre': 'Cobertura médica integral',
                  'detalle': '100% de cobertura en prestaciones de rehabilitación vinculadas a la '
                             'discapacidad (Ley 24.901).',
                  'normativa': 'Ley 24.901'},
                 {'nombre': 'Medicamentos sin cargo',
                  'detalle': 'Medicamentos relacionados con la discapacidad sin costo.',
                  'normativa': 'Ley 24.901'},
                 {'nombre': 'Prestaciones de apoyo',
                  'detalle': 'Asistente personal, acompañante terapéutico, transporte sanitario.',
                  'normativa': 'Ley 24.901'}]},
 {'categoria': 'Transporte',
  'icono': '🚌',
  'beneficios': [{'nombre': 'Transporte público gratuito',
                  'detalle': '100% de descuento en colectivos, trenes y subtes de todo el país. '
                             'Registrar CUD en SUBE.',
                  'normativa': 'Ley 22.431 / CNRT',
                  'url': 'https://www.argentina.gob.ar/servicio/registrar-certificado-unico-de-discapacidad-cud-en-la-sube'},
                 {'nombre': 'Franquicia aerocomercial',
                  'detalle': 'Descuento en pasajes aéreos de cabotaje para la persona y un '
                             'acompañante.',
                  'normativa': 'Resolución ANAC'}]},
 {'categoria': 'Educación',
  'icono': '📚',
  'beneficios': [{'nombre': 'Educación especial e integrada',
                  'detalle': 'Maestras integradoras y apoyos pedagógicos financiados por la obra '
                             'social.',
                  'normativa': 'Ley 26.206 / Ley 24.901'},
                 {'nombre': 'Ayuda escolar anual',
                  'detalle': 'Asignación familiar especial para hijo con discapacidad (ANSES).',
                  'normativa': 'Ley 24.714',
                  'url': 'https://www.anses.gob.ar/informacion/asignacion-familiar-por-hijo-con-discapacidad'}]},
 {'categoria': 'Trabajo',
  'icono': '💼',
  'beneficios': [{'nombre': 'Cupo laboral en el Estado',
                  'detalle': '4% de los cargos del Estado Nacional deben ser cubiertos por '
                             'personas con discapacidad.',
                  'normativa': 'Ley 22.431 art. 8'},
                 {'nombre': 'Incentivos para empleadores',
                  'detalle': 'Empresas que contraten personas con CUD tienen reducciones en '
                             'contribuciones patronales.',
                  'normativa': 'Ley 22.431'}]},
 {'categoria': 'Impuestos y económico',
  'icono': '💰',
  'beneficios': [{'nombre': 'Exención en Ganancias',
                  'detalle': 'Las personas con CUD pueden estar exentas del impuesto a las '
                             'ganancias.',
                  'normativa': 'Ley 20.628'},
                 {'nombre': 'Pensión no contributiva por invalidez',
                  'detalle': 'Para personas sin obra social ni ingresos suficientes con '
                             'discapacidad mayor al 76%.',
                  'normativa': 'Ley 18.910',
                  'url': 'https://www.argentina.gob.ar/andis/pensiones'},
                 {'nombre': 'Exención en patente de vehículos',
                  'detalle': 'Exención o reducción en el pago de patente del vehículo adaptado.',
                  'normativa': 'Varía por provincia'}]},
 {'categoria': 'Vivienda',
  'icono': '🏠',
  'beneficios': [{'nombre': 'Accesibilidad en viviendas del Estado',
                  'detalle': 'Prioridad en acceso a viviendas sociales accesibles.',
                  'normativa': 'Ley 24.314'}]}]


JUNTAS_POR_PROVINCIA = {'Buenos Aires': {'nombre_organismo': 'Dirección Provincial de Discapacidad — Provincia de Buenos '
                                      'Aires',
                  'url_turno': 'https://www.gba.gob.ar/discapacidad',
                  'telefono': '0800-222-2427',
                  'email': 'discapacidad@gba.gob.ar',
                  'turno_online': True,
                  'tiempo_espera_estimado': '20-45 días',
                  'nota': 'La provincia tiene juntas en todos los municipios. Ver listado completo '
                          'en el portal provincial.',
                  'sedes': [{'nombre': 'Dirección Provincial — La Plata',
                             'direccion': 'Calle 8, esq. 67 Nº 1689, La Plata'},
                            {'nombre': 'Hospital R. Rossi — La Plata',
                             'direccion': 'Calle 37 e/ 116 y 117, La Plata',
                             'telefono': '0221-4822-8821'},
                            {'nombre': 'Hospital San Martín — La Plata',
                             'direccion': 'Calle 69 y 116, La Plata',
                             'telefono': '0221-4211190'},
                            {'nombre': 'Hospital Paroissien — La Matanza',
                             'direccion': 'Ruta 3 km. 21, Isidro Casanova',
                             'telefono': '4669-2828'},
                            {'nombre': 'Hospital Melo — Lanús',
                             'direccion': 'Av. Villa de Luján 3050, Remedios de Escalada',
                             'telefono': '4246-0868'},
                            {'nombre': 'Dirección de Discapacidad — Mar del Plata',
                             'direccion': 'Pescadores 456, Mar del Plata',
                             'telefono': '0223-4803053'},
                            {'nombre': 'Dirección de Discapacidad — Bahía Blanca',
                             'direccion': 'Chiclana 451, Bahía Blanca',
                             'telefono': '0291-5506000'}]},
 'CABA': {'nombre_organismo': 'COPIDIS — Comisión para la Plena Participación e Inclusión de las '
                              'Personas con Discapacidad',
          'url_turno': 'https://www.buenosaires.gob.ar/copidis/certificacion-de-discapacidad',
          'telefono': '0800-999-2727 opción 3',
          'email': 'discapacidadba@buenosaires.gob.ar',
          'turno_online': True,
          'tiempo_espera_estimado': '15-30 días',
          'nota': 'Las juntas en CABA están distribuidas por tipo de discapacidad.',
          'sedes': [{'nombre': 'IREP — Discapacidad Motora',
                     'direccion': 'Echeverría 955, Belgrano',
                     'telefono': '4781-6071 int. 1083',
                     'tipo': 'motora'},
                    {'nombre': 'Hospital Rocca — Motora y Auditiva',
                     'direccion': 'Segurola 1949, Flores',
                     'telefono': '4630-4728',
                     'tipo': 'motora/auditiva'},
                    {'nombre': 'Hospital Santa Lucía — Visual',
                     'direccion': 'Av. San Juan 2021 y Sarandí, San Cristóbal',
                     'telefono': '4121-3193',
                     'tipo': 'visual'},
                    {'nombre': 'Hospital Álvear — Salud Mental adultos',
                     'direccion': 'Warnes 2630, Agronomía',
                     'telefono': '4521-0983',
                     'tipo': 'psicosocial'},
                    {'nombre': 'Hospital Piñero — Menores de 18 años',
                     'direccion': 'Varela 1307 y Viola, Flores',
                     'telefono': '4631-8601',
                     'tipo': 'todas (menores)'},
                    {'nombre': 'Hospital Penna — Visceral adultos',
                     'direccion': 'Pedro Chutro 3380, Parque Patricios',
                     'telefono': '4911-3030 int. 106',
                     'tipo': 'visceral'}]},
 'Catamarca': {'nombre_organismo': 'Dirección de Asistencia Integral a Personas con Discapacidad',
               'url_turno': 'https://www.catamarca.gov.ar',
               'telefono': '(03833) 437921 / 437913',
               'email': 'discapacidadctca@yahoo.com.ar',
               'turno_online': False,
               'tiempo_espera_estimado': '15-30 días',
               'sedes': [{'nombre': 'Sede Central',
                          'direccion': 'Av. Juan D. Perón 11 esq. Av. Arturo Illia, San Fernando '
                                       'del Valle de Catamarca',
                          'telefono': '(03833) 437921'}]},
 'Chaco': {'nombre_organismo': 'Junta Central Evaluadora — Hospital Julio C. Perrando',
           'url_turno': 'https://www.chaco.gov.ar',
           'telefono': '(03722) 425050 / 442399 / 456446',
           'email': None,
           'turno_online': False,
           'tiempo_espera_estimado': '15-30 días',
           'sedes': [{'nombre': 'Hospital Julio C. Perrando — Resistencia (Junta Central)',
                      'direccion': 'Av. 9 de Julio 1099, Resistencia',
                      'telefono': '(03722) 425050'},
                     {'nombre': 'Hospital General Güemes — Juan José Castelli',
                      'direccion': 'Av. San Martín 1050, Juan José Castelli',
                      'telefono': '(03732) 471006'},
                     {'nombre': 'Hospital 9 de Julio — Las Breñas',
                      'direccion': 'Arbo y Blanco S/N, Las Breñas',
                      'telefono': '(03731) 460034'},
                     {'nombre': 'Hospital 4 de Julio — Presidencia R. Sáenz Peña',
                      'direccion': 'Malvinas Argentinas S/N 1350',
                      'telefono': '(03644) 424568'},
                     {'nombre': 'Hospital Salvador Mazza — Villa Ángela',
                      'direccion': 'Josefa Rosello y Freire, Villa Ángela',
                      'telefono': '(03735) 429065'}]},
 'Chubut': {'nombre_organismo': 'Secretaría de Salud — Dirección de Discapacidad',
            'url_turno': 'https://www.chubut.gov.ar',
            'telefono': '0800 222 8582',
            'email': None,
            'turno_online': False,
            'tiempo_espera_estimado': '15-30 días',
            'sedes': [{'nombre': 'Sede Central — Rawson', 'direccion': 'Moreno 555, Rawson'},
                      {'nombre': 'Hospital Regional — Comodoro Rivadavia',
                       'direccion': 'H. Yrigoyen 950, Comodoro Rivadavia',
                       'telefono': '(0297) 4473563'},
                      {'nombre': 'Hospital Zonal — Esquel',
                       'direccion': 'Roca 145, Esquel',
                       'telefono': '(02945) 451224'},
                      {'nombre': 'Hospital Sub-zonal — Puerto Madryn',
                       'direccion': 'Pujol 247, Puerto Madryn',
                       'telefono': '(02964) 453030'},
                      {'nombre': 'Hospital Sub-zonal — Rawson',
                       'direccion': 'Julio A. Roca 545, Rawson',
                       'telefono': '(02965) 481260'},
                      {'nombre': 'Serv. Rehabilitación Pichi Anul — Trelew',
                       'direccion': 'San Martín 518, Trelew',
                       'telefono': '(02965) 427670'},
                      {'nombre': 'Hospital Trevelin',
                       'direccion': 'Av. San Martín 995, Trevelin',
                       'telefono': '(02965) 480132'}]},
 'Córdoba': {'nombre_organismo': 'Junta Central Evaluadora de Personas — Ministerio de Salud',
             'url_turno': 'https://www.cba.gov.ar/discapacidad',
             'telefono': '(0351) 4341511 / 4688692',
             'email': None,
             'turno_online': True,
             'tiempo_espera_estimado': '15-30 días',
             'sedes': [{'nombre': 'Junta Central Evaluadora',
                        'direccion': 'Av. Vélez Sarsfield 2311, Córdoba Capital',
                        'telefono': '(0351) 4341511'},
                       {'nombre': 'Centro Nacional de Reconocimientos Médicos',
                        'direccion': '9 de Julio 360, Capital',
                        'telefono': '(0351) 421-5304'},
                       {'nombre': 'Hospital de Córdoba',
                        'direccion': 'Av. Patria 656, Barrio Pueyrredón, Capital'},
                       {'nombre': 'Hospital de Niños Santísima Trinidad',
                        'direccion': 'Bajada Pucará S/N, Barrio Crisol'},
                       {'nombre': 'Hospital Regional Dr. Romagosa — Dean Funes',
                        'direccion': 'Colón 247, Dean Funes'},
                       {'nombre': 'Hospital Central San Antonio de Padua — Río Cuarto',
                        'direccion': 'Gral. Mosconi 48, Río Cuarto'},
                       {'nombre': 'Hospital Regional Pasteur — Villa María',
                        'direccion': 'Pasteur Mendoza 2152, Villa María'}]},
 'Corrientes': {'nombre_organismo': 'Junta Central Evaluadora de Personas — Ministerio de Salud',
                'url_turno': 'https://salud.corrientes.gov.ar',
                'telefono': '(03783) 424842',
                'email': None,
                'turno_online': False,
                'tiempo_espera_estimado': '15-30 días',
                'sedes': [{'nombre': 'Junta Central — Corrientes Capital',
                           'direccion': 'Santa Fe 762, Corrientes Capital',
                           'telefono': '(03783) 424842'},
                          {'nombre': 'Instituto Correntino de Ayuda al Lisiado',
                           'direccion': 'San Lorenzo 784, Corrientes',
                           'telefono': '(03783) 424642'},
                          {'nombre': 'Hospital Dr. Camilo Maniagurria — Goya',
                           'direccion': 'Av. Mazzanti 550, Goya',
                           'telefono': '(03777) 422283'}]},
 'Entre Ríos': {'nombre_organismo': 'IPRODICH — Instituto Provincial del Discapacitado de Entre '
                                    'Ríos',
                'url_turno': 'https://www.iprodich.gob.ar',
                'telefono': '(0343) 4208280 / 4208281',
                'email': 'ipdiscapacidad@yahoo.com.ar',
                'turno_online': False,
                'tiempo_espera_estimado': '15-30 días',
                'sedes': [{'nombre': 'IPRODICH — Sede Central Paraná',
                           'direccion': 'Gregoria Matorras de San Martín 861 y Azcuénaga, Paraná',
                           'telefono': '(0343) 4208280'}]},
 'Formosa': {'nombre_organismo': 'Junta Central Evaluadora — Ministerio de Desarrollo Humano',
             'url_turno': 'https://www.formosa.gob.ar',
             'telefono': '(03717) 436446',
             'email': None,
             'turno_online': False,
             'tiempo_espera_estimado': '15-30 días',
             'sedes': [{'nombre': 'Junta Central — Centro de Día',
                        'direccion': 'Junín y Yunká, Formosa Capital',
                        'telefono': '(03717) 436446'},
                       {'nombre': 'Ministerio de Desarrollo Humano',
                        'direccion': 'Santa Fe 1260, Formosa Capital',
                        'telefono': '(03717) 427515'},
                       {'nombre': 'Hospital Dr. Cruz Felipe Arnedo — Clorinda',
                        'direccion': 'San Martín y Los Andes, Clorinda',
                        'telefono': '(03718) 422800'},
                       {'nombre': 'Hospital Laguna Blanca',
                        'direccion': 'Esteban Florentín S/N, Laguna Blanca',
                        'telefono': '(03718) 470020'}]},
 'Jujuy': {'nombre_organismo': 'Departamento Provincial de Rehabilitación — Ministerio de '
                               'Bienestar Social',
           'url_turno': 'https://salud.jujuy.gob.ar',
           'telefono': '(0388) 4234243 / 44221308',
           'email': None,
           'turno_online': False,
           'tiempo_espera_estimado': '15-30 días',
           'sedes': [{'nombre': 'Sede Central — San Salvador de Jujuy',
                      'direccion': 'Independencia 41, San Salvador de Jujuy',
                      'telefono': '(0388) 4234243'}]},
 'La Pampa': {'nombre_organismo': 'Dirección de Discapacidad — Ministerio de Bienestar Social',
              'url_turno': 'https://www.lapampa.gob.ar',
              'telefono': '(02954) 453953',
              'email': None,
              'turno_online': False,
              'tiempo_espera_estimado': '10-20 días',
              'sedes': [{'nombre': 'Dirección de Discapacidad — Santa Rosa',
                         'direccion': 'Av. Julio A. Roca 851, Santa Rosa',
                         'telefono': '(02954) 453953'},
                        {'nombre': 'Centro Abudara — General Pico',
                         'direccion': 'S/C, S/N (ex Hospital Ferroviario), General Pico',
                         'telefono': '(02302) 431994'}]},
 'La Rioja': {'nombre_organismo': 'Juntas Evaluadoras — Ministerio de Salud',
              'url_turno': 'https://salud.larioja.gov.ar',
              'telefono': '(03822) 453552',
              'email': None,
              'turno_online': False,
              'tiempo_espera_estimado': '15-30 días',
              'sedes': [{'nombre': 'Hospital Enrique Vera Barros — La Rioja Capital',
                         'direccion': 'Olta S/N, La Rioja Capital',
                         'telefono': '(03822) 453552'},
                        {'nombre': 'Hospital San Nicolás — Aimogasta',
                         'direccion': 'Casimiro Godoy S/N, Aimogasta',
                         'telefono': '(03827) 429004'},
                        {'nombre': 'Hospital Luis Agote — Chamical',
                         'direccion': 'Constantino Carver esq. El Chacho, Chamical',
                         'telefono': '(03826) 429020'},
                        {'nombre': 'Hospital Luis Pasteur — Chepes',
                         'direccion': 'San Juan 255, Chepes',
                         'telefono': '(03821) 429105'},
                        {'nombre': 'Hospital Eleazar H. Mota — Chilecito',
                         'direccion': 'Cabero 500, Chilecito'}]},
 'Mendoza': {'nombre_organismo': 'Gerencia de Discapacidad — Ministerio de Salud',
             'url_turno': 'https://www.mendoza.gov.ar',
             'telefono': '(0261) 4254780',
             'email': None,
             'turno_online': True,
             'tiempo_espera_estimado': '15-30 días',
             'sedes': [{'nombre': 'Junta Central — Mendoza Capital',
                        'direccion': 'España 922, Mendoza Capital',
                        'telefono': '(0261) 4254780'},
                       {'nombre': 'Gerencia de Discapacidad',
                        'direccion': 'Colón 659, Mendoza Capital',
                        'telefono': '(0261) 4254780 int. 113'},
                       {'nombre': 'Junta — Las Heras',
                        'direccion': 'San Miguel 1457, Las Heras',
                        'telefono': '4378126'},
                       {'nombre': 'Junta — Guaymallén',
                        'direccion': 'Mitre y Godoy Cruz, Guaymallén',
                        'telefono': '4498204'},
                       {'nombre': 'Junta — Maipú',
                        'direccion': 'Barcala 155 e/Pescara y Padre Vázquez, Maipú',
                        'telefono': '4974285'},
                       {'nombre': 'Junta — San Rafael',
                        'direccion': 'Córdoba 156, San Rafael',
                        'telefono': '(0260) 449279'},
                       {'nombre': 'Junta — San Martín',
                        'direccion': 'Almirante Brown y España, San Martín',
                        'telefono': '(0263) 420362'},
                       {'nombre': 'Junta — Tunuyán / San Carlos',
                        'direccion': 'Hospital Regional Dr. A. Scaravelli, Tunuyán',
                        'telefono': '(02622) 411963'},
                       {'nombre': 'Junta — General Alvear',
                        'direccion': 'San Rafael 175, General Alvear',
                        'telefono': '(02625) 425861'},
                       {'nombre': 'Junta — Malargüe',
                        'direccion': 'Vacunatorio Central, Malargüe',
                        'telefono': '(02627) 4710505'}]},
 'Misiones': {'nombre_organismo': 'Dirección de Discapacidad — Ministerio de Salud Pública',
              'url_turno': 'https://salud.misiones.gob.ar',
              'telefono': '(0376) 444082 / 441426',
              'email': 'discapacidad_misiones@hotmail.com',
              'turno_online': False,
              'tiempo_espera_estimado': '10-25 días',
              'sedes': [{'nombre': 'Junta Central — Posadas',
                         'direccion': 'Junín y Tucumán, Posadas',
                         'telefono': '(0376) 444082'},
                        {'nombre': 'Junta Evaluadora — Eldorado',
                         'direccion': 'Calle Mbororé, Eldorado'},
                        {'nombre': 'Hospital SAMIC — Oberá',
                         'direccion': 'Calle Pincén y Federación S/N, Oberá',
                         'telefono': '03755-421226',
                         'email': 'cudzonacentroturuguay@gmail.com'},
                        {'nombre': 'Zona Sur — Leandro N. Alem',
                         'direccion': '25 de Mayo 1076, Leandro N. Alem',
                         'telefono': '03754-533509'},
                        {'nombre': 'Junta — Jardín América',
                         'direccion': 'Fray Bonifacio Ortiz y Ruta Provincial 7, Jardín América',
                         'telefono': '3743-610701'},
                        {'nombre': 'Hospital de Iguazú',
                         'direccion': 'Victoria Aguirre 142, Puerto Iguazú',
                         'telefono': '3755-546269'},
                        {'nombre': 'CIC — Andresito',
                         'direccion': 'Av. Corrientes y Catamarca, Andresito',
                         'telefono': '3757-304839'},
                        {'nombre': 'Junta — San Vicente',
                         'direccion': 'Calle Abel Sínuka 48, San Vicente',
                         'telefono': '3755-546269'},
                        {'nombre': 'Hospital San Antonio — San Antonio',
                         'direccion': 'Av. Andrés Guacurarí 750, San Antonio'}]},
 'Neuquén': {'nombre_organismo': 'JUCAID — Junta Coordinadora para la Atención Integral del '
                                 'Discapacitado',
             'url_turno': 'https://www.neuquen.gov.ar',
             'telefono': '(0299) 4495552',
             'email': None,
             'turno_online': False,
             'tiempo_espera_estimado': '10-20 días',
             'sedes': [{'nombre': 'JUCAID — Neuquén Capital',
                        'direccion': 'Salta 265, Neuquén Capital (CP 8300)',
                        'telefono': '(0299) 4495552'}]},
 'Río Negro': {'nombre_organismo': 'Consejo Provincial del Discapacitado — Junta Central',
               'url_turno': 'https://www.rionegro.gov.ar',
               'telefono': '(02920) 421833',
               'email': None,
               'turno_online': False,
               'tiempo_espera_estimado': '10-20 días',
               'sedes': [{'nombre': 'Consejo Provincial del Discapacitado — Viedma',
                          'direccion': 'Laprida 226, Viedma',
                          'telefono': '(02920) 421833'}]},
 'Salta': {'nombre_organismo': 'Junta Central Evaluadora — Secretaría de Asistencia Médica',
           'url_turno': 'https://www.salta.gov.ar',
           'telefono': '(0387) 4375146 / 4314866',
           'email': None,
           'turno_online': False,
           'tiempo_espera_estimado': '15-30 días',
           'sedes': [{'nombre': 'Junta Central Evaluadora — Salta Capital',
                      'direccion': 'Gral. Güemes 562, Salta Capital',
                      'telefono': '(0387) 4375146'},
                     {'nombre': 'Secretaría de Asistencia Médica',
                      'direccion': 'Lerma 800, Salta Capital',
                      'telefono': '(0387) 4375146'}]},
 'San Juan': {'nombre_organismo': 'Dirección de la Persona con Capacidades Especiales',
              'url_turno': 'https://www.sanjuan.gov.ar',
              'telefono': '(0264) 4216606',
              'email': None,
              'turno_online': False,
              'tiempo_espera_estimado': '15-30 días',
              'sedes': [{'nombre': 'Dirección de la Persona con Capacidades Especiales',
                         'direccion': 'Gral. Acha 534 (s), San Juan Capital',
                         'telefono': '(0264) 4216606'},
                        {'nombre': 'Sub-Junta Médica Evaluadora',
                         'direccion': 'Mendoza 398 (sur), San Juan Capital',
                         'telefono': '(0264) 4226609'}]},
 'San Luis': {'nombre_organismo': 'Centro de Referencia Provincial de Rehabilitación',
              'url_turno': 'https://www.sanluis.gov.ar',
              'telefono': '(02652) 425046 / 431079',
              'email': None,
              'turno_online': False,
              'tiempo_espera_estimado': '10-20 días',
              'sedes': [{'nombre': 'Centro de Referencia Provincial de Rehabilitación',
                         'direccion': 'Ciudad del Rosario y Pasteur, San Luis Capital',
                         'telefono': '(02652) 425046'}]},
 'Santa Cruz': {'nombre_organismo': 'Área de Discapacidad — Subsecretaría de Salud Pública',
                'url_turno': 'https://www.santacruz.gov.ar',
                'telefono': '(02966) 426173 / 420535',
                'email': None,
                'turno_online': False,
                'tiempo_espera_estimado': '10-20 días',
                'sedes': [{'nombre': 'Área de Discapacidad — Río Gallegos',
                           'direccion': 'Salta 55, Río Gallegos',
                           'telefono': '(02966) 426173'}]},
 'Santa Fe': {'nombre_organismo': 'Dirección Provincial de Inclusión de Personas con Discapacidad',
              'url_turno': 'https://www.santafe.gov.ar/discapacidad',
              'telefono': '0800-888-3588',
              'email': None,
              'turno_online': True,
              'tiempo_espera_estimado': '10-25 días',
              'sedes': [{'nombre': 'Junta Central — Santa Fe Capital',
                         'direccion': 'Dr. Zavalla 3361 2° piso, Santa Fe Capital',
                         'telefono': '(0342) 4572481'},
                        {'nombre': 'Dirección Provincial de Rehabilitación',
                         'direccion': 'Bv. Zavalla 3361, Santa Fe',
                         'telefono': '(0342) 4572483'},
                        {'nombre': 'CEMAR — Rosario (2da. Circunscripción)',
                         'direccion': '9 de Julio 325, Rosario',
                         'telefono': '(0341) 4721164'},
                        {'nombre': 'Hospital Granadero Baigorria',
                         'direccion': 'Av. San Martín 1645, Granadero Baigorria',
                         'telefono': '(0341) 4721164'},
                        {'nombre': 'SAMCO Reconquista',
                         'direccion': 'Hipólito Irigoyen 1580, Reconquista',
                         'telefono': '(03482) 420012'},
                        {'nombre': 'SAMCO Rafaela',
                         'direccion': 'Lisandro de la Torre 373, Rafaela',
                         'telefono': '(03492) 421621'},
                        {'nombre': 'Hospital San José — Casilda',
                         'direccion': '9 de Julio 2351, Casilda',
                         'telefono': '(03464) 422382'},
                        {'nombre': 'Hospital Alejandro Gutiérrez — Venado Tuerto',
                         'direccion': 'Gutiérrez 55, Venado Tuerto',
                         'telefono': '(03462) 439098'}]},
 'Santiago del Estero': {'nombre_organismo': 'Dirección Provincial de Discapacidad',
                         'url_turno': 'https://www.santiago.gov.ar',
                         'telefono': '(0385) 4242207',
                         'email': None,
                         'turno_online': False,
                         'tiempo_espera_estimado': '15-30 días',
                         'sedes': [{'nombre': 'Dirección Provincial de Discapacidad',
                                    'direccion': 'Güemes y Misiones, Santiago del Estero Capital',
                                    'telefono': '(0385) 4242207'}]},
 'Tierra del Fuego': {'nombre_organismo': 'Secretaría General de Acción Social — Dirección de '
                                          'Discapacidad',
                      'url_turno': 'https://www.tierradelfuego.gob.ar',
                      'telefono': '(02901) 431159',
                      'email': None,
                      'turno_online': False,
                      'tiempo_espera_estimado': '10-20 días',
                      'sedes': [{'nombre': 'Dirección de Discapacidad — Ushuaia',
                                 'direccion': 'San Martín 450, 1° Piso, Ushuaia',
                                 'telefono': '(02901) 431159'}]},
 'Tucumán': {'nombre_organismo': 'Junta de Evaluación de Discapacidad y Categorización de '
                                 'Prestadores',
             'url_turno': 'https://salud.tucuman.gov.ar',
             'telefono': '(0381) 452-6291 / 6292',
             'email': None,
             'turno_online': False,
             'tiempo_espera_estimado': '15-30 días',
             'sedes': [{'nombre': 'Junta de Evaluación — San Miguel de Tucumán',
                        'direccion': 'Alberdi 416, San Miguel de Tucumán',
                        'telefono': '(0381) 452-6291'}]}}


FAQ = [{'pregunta': '¿El trámite del CUD es gratuito?',
  'respuesta': 'Sí, el trámite del CUD es completamente gratuito. Ningún organismo puede cobrar '
               'por la emisión del certificado.'},
 {'pregunta': '¿El CUD vence?',
  'respuesta': 'Desde la Resolución ANDIS 322/2023, el CUD se otorga sin fecha de vencimiento '
               'mientras las condiciones certificantes se mantengan. Los CUD anteriores mantienen '
               'su validez.'},
 {'pregunta': '¿Puedo tramitar el CUD si vivo en el interior del país?',
  'respuesta': 'Sí. Cada provincia tiene su propia Junta Evaluadora. El trámite se realiza en la '
               'jurisdicción donde residís según tu DNI.'},
 {'pregunta': '¿Qué pasa si me rechazan el CUD?',
  'respuesta': 'Podés apelar la resolución dentro de los 30 días hábiles ante la misma Junta o el '
               'organismo provincial. Es recomendable presentar documentación adicional.'},
 {'pregunta': '¿El CUD es lo mismo que la pensión por invalidez?',
  'respuesta': 'No. El CUD certifica la discapacidad. La pensión es una prestación económica '
               'diferente que puede solicitarse con el CUD pero tiene requisitos propios.'},
 {'pregunta': '¿Puedo tener CUD y trabajar?',
  'respuesta': 'Sí. Tener CUD no impide trabajar. El cupo laboral del 4% en el Estado está pensado '
               'para personas con CUD que buscan empleo.'},
 {'pregunta': '¿Mi obra social está obligada a cubrir todo?',
  'respuesta': 'Sí. Bajo la Ley 24.901, obras sociales y prepagas deben cubrir el 100% de las '
               'prestaciones de rehabilitación. Si se niegan, denunciá ante la Superintendencia de '
               'Salud: 0800-222-72583.'},
 {'pregunta': '¿Cómo registro el CUD en la SUBE?',
  'respuesta': 'Online en sube.gob.ar o en una terminal SUBE. Necesitás el número de CUD y el '
               'número de tarjeta SUBE. El descuento del 100% se activa automáticamente.'},
 {'pregunta': '¿El CUD digital tiene la misma validez que el físico?',
  'respuesta': 'Sí. El CUD digital en la app Mi Argentina tiene exactamente la misma validez legal '
               'e incluye código QR para verificación.'},
 {'pregunta': '¿Cuánto tiempo tarda el trámite?',
  'respuesta': 'Entre 30 y 90 días hábiles desde la evaluación según la provincia. CABA y Buenos '
               'Aires suelen tener mayor demanda.'}]

# ── SUBE_INFO ─────────────────────────────────────────────────────────────────
# Registro del CUD en la tarjeta SUBE para transporte público gratuito.
# Fuente: Ministerio de Transporte / SUBE — sube.gob.ar
# Normativa: Ley 22.431 art. 22 / Resolución CNRT 1018/2018
SUBE_INFO = {
    'titulo': 'Registro del CUD en la tarjeta SUBE',
    'descripcion': (
        'El registro del CUD en la tarjeta SUBE es un trámite OBLIGATORIO e independiente '
        'del CUD. Sin este paso el descuento en transporte público NO se activa aunque '
        'ya tengas el CUD en mano.'
    ),
    'beneficio': {
        'descuento': '100%',
        'medios': ['colectivo', 'tren', 'subte', 'premetro'],
        'alcance': 'Todo el país (red SUBE nacional)',
        'acompanante': (
            'El titular puede viajar con un acompañante con el mismo descuento '
            'cuando lo necesite por razón de su discapacidad (acreditar con CUD).'
        ),
        'normativa': 'Ley 22.431 art. 22 / Resolución CNRT 1018/2018',
    },
    'requisitos': [
        'Tener el CUD otorgado (número de CUD o DNI vinculado)',
        'Tarjeta SUBE registrada a nombre del titular (no puede ser una SUBE anónima)',
        'Número de tarjeta SUBE (impreso en el reverso, 16 dígitos)',
        'Cuenta en argentina.gob.ar para el trámite online (opcional — también se puede hacer presencialmente)',
    ],
    'canales': [
        {
            'canal': 'Online — sube.gob.ar',
            'url': 'https://www.sube.gob.ar',
            'pasos': [
                'Ingresá a sube.gob.ar',
                'Iniciá sesión con tu cuenta de argentina.gob.ar (podés crearla gratis)',
                'Seleccioná "Registrar beneficio por discapacidad"',
                'Ingresá el número de CUD y el número de SUBE (16 dígitos del reverso)',
                'Confirmá los datos y enviá el formulario',
                'El descuento se activa en la próxima carga o uso de la tarjeta (24-48 hs)',
            ],
        },
        {
            'canal': 'Trámite oficial Argentina.gob.ar',
            'url': 'https://www.argentina.gob.ar/servicio/registrar-certificado-unico-de-discapacidad-cud-en-la-sube',
            'pasos': [
                'Ingresá al trámite oficial en argentina.gob.ar',
                'Completá el formulario con datos del CUD y la SUBE',
                'El sistema vincula el beneficio automáticamente',
            ],
        },
        {
            'canal': 'Terminal SUBE (presencial)',
            'url': None,
            'pasos': [
                'Acercate a cualquier terminal SUBE habilitada (kioscos, supermercados, Correo Argentino)',
                'Apoyá la tarjeta SUBE en el lector',
                'Seleccioná la opción "Beneficios por discapacidad"',
                'Seguí las instrucciones en pantalla ingresando tu número de CUD',
                'El descuento queda registrado en la tarjeta al instante',
            ],
        },
        {
            'canal': 'Centro de atención ANDIS',
            'url': 'https://www.argentina.gob.ar/tramites/sacar-turno-andis',
            'pasos': [
                'Sacá turno en ANDIS',
                'Presentá DNI y tarjeta SUBE',
                'El agente realiza el registro durante la atención',
            ],
        },
    ],
    'activacion': {
        'online': '24 a 48 horas después del registro',
        'terminal': 'Inmediata',
        'centro_andis': 'Inmediata durante la atención',
        'nota': (
            'Si el descuento no se activa luego de 72 hs del registro online, '
            'llamar a la línea SUBE: 0800-777-7823 (gratuito, lun-vie 8-20 hs).'
        ),
    },
    'renovacion': (
        'Como el CUD ya no vence (Resolución ANDIS 322/2023), el beneficio SUBE '
        'tampoco vence. Solo deberás actualizarlo si cambiás de tarjeta SUBE.'
    ),
    'sube_perdida_o_robo': {
        'pasos': [
            'Bloqueá la SUBE en sube.gob.ar o llamando al 0800-777-7823',
            'Solicitá una nueva tarjeta SUBE registrada',
            'Repetí el registro del beneficio por discapacidad con la nueva tarjeta',
        ],
        'nota': 'El saldo y el beneficio de discapacidad se transfieren a la nueva tarjeta.',
    },
    'contacto': {
        'telefono': '0800-777-7823',
        'horario': 'Lunes a viernes de 8 a 20 hs',
        'gratuito': True,
        'web': 'https://www.sube.gob.ar',
    },
    'preguntas_frecuentes': [
        {
            'pregunta': '¿Puedo usar la SUBE de otra persona para el descuento?',
            'respuesta': (
                'No. El beneficio se vincula a UNA tarjeta SUBE registrada a nombre del titular. '
                'El uso de la tarjeta de otra persona implica la pérdida del beneficio.'
            ),
        },
        {
            'pregunta': '¿El descuento aplica a cualquier colectivo del país?',
            'respuesta': (
                'Sí, en todos los servicios de transporte público que operen con SUBE: '
                'colectivos urbanos e interurbanos, trenes del AMBA y subte de CABA. '
                'Para servicios de larga distancia consultá con la empresa de transporte.'
            ),
        },
        {
            'pregunta': '¿Qué pasa si ya tengo SUBE pero no está registrada?',
            'respuesta': (
                'Primero tenés que registrar la tarjeta a tu nombre en sube.gob.ar. '
                'Una SUBE anónima no puede recibir el beneficio de discapacidad.'
            ),
        },
        {
            'pregunta': '¿El acompañante también viaja gratis?',
            'respuesta': (
                'Sí, cuando la persona con discapacidad necesita asistencia para viajar, '
                'un acompañante también viaja sin cargo. El titular debe presentar el CUD '
                'al chofer o guarda si se lo solicitan.'
            ),
        },
    ],
}
